public enum CombatState {
    IDLE,
    READY,
    SELECTING_COMMAND,
    SELECTING_BOOST,
    SELECTING_TARGET,
    WINDUP,
    ATTACKING,
    MULTI_HIT,
    HIT_PAUSE,
    RECOVERY,
    HURT,
    DEFENDING,
    DEAD
}